spring:
  application:
    name: zadmin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.9.105:43306/z-admin?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: z-admin
    password: Zs2806478963

#  datasource:
#    dynamic:
#      primary:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:mysql://192.168.9.105:43306/z-admin?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
#        username: z-admin
#        password: Zs2806478963
#        driver-class-name: com.mysql.cj.jdbc.Driver
#      ds2:
#        type: com.zaxxer.hikari.HikariDataSource
#        url: jdbc:mysql://192.168.9.105:43306/z-ds2?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
#        username: z-ds2
#        password: Zs2806478963
#        driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      # 请将此处修改为你 Ubuntu 服务器的实际 IP 地址
      host: 192.168.9.105
      # 对应 docker-compose.redis.yaml 中的映射端口 46379
      port: 46379
      # 对应 docker-compose.redis.yaml 中的密码
      password: Zs2806478963
      database: 0
      timeout: 5s


logging:
  level:
    com.easy.query: debug
