spring:
  application:
    name: zadmin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.9.105:43306/z-admin?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: z-admin
    password: Zs2806478963
  data:
    redis:
      host: 192.168.9.105
      port: 46379
      password: Zs2806478963
      database: 0
      timeout: 5s

logging:
  level:
    com.easy.query: debug
