spring:
  application:
    name: zadmin
  threads:
    virtual:
      enabled: true
  datasource:
    dynamic:
      primary:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://192.168.9.105:25432/postgres?currentSchema=public&reWriteBatchedInserts=true&socketTimeout=60&connectTimeout=60&tcpKeepAlive=true
        username: postgres
        password: Zs2806478963
        driver-class-name: org.postgresql.Driver
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.9.105:43306/z-ds1?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
        username: z-ds1
        password: Zs2806478963
        driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: 192.168.9.105
      port: 46379
      password: Zs2806478963
      database: 0
      timeout: 5s
      lettuce:
        pool:
          max-active: 100
          max-wait: 30s
          max-idle: 30
          min-idle: 10

  jackson: # Jackson 全局配置
    default-property-inclusion: ALWAYS # 属性默认全部序列化/反序列化
    time-zone: GMT+8 # 时区配置
    deserialization: # 反序列化配置
      FAIL_ON_UNKNOWN_PROPERTIES: false # 忽略未知字段
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true # 空字符串反序列化为 null
    datatype: # 数据类型相关配置
      datetime: # 日期时间配置
        WRITE_DATES_AS_TIMESTAMPS: false # 日期时间不写为时间戳
    mapper: # 映射器配置
      SORT_CREATOR_PROPERTIES_FIRST: true # 构造参数属性优先排序
      SORT_PROPERTIES_ALPHABETICALLY: false # 不按字母序排序属性
server:
  tomcat:
    max-connections: 20000          # 可适当增大
    accept-count: 200               # 增大等待队列
    connection-timeout: 30s
    keep-alive-timeout: 60s
    max-keep-alive-requests: 200
    processor-cache: 500            # 增大处理器缓存
    max-http-form-post-size: 100MB
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/javascript
    min-response-size: 1024


logging:
  file:
    name: zlogs/zadmin.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  level:
    com.easy.query: info
    org.redisson: debug
    org.redisson.client: debug
    org.redisson.connection: info
    org.redisson.command: debug
    io.netty: info


app:
  snowflake:
    epoch: 1704067200000  # 2024-01-01 00:00:00
    worker-id: 1
  request-cache:
    max-size: 100MB
  auth:
    enabled: false  # 是否启用安全校验,开发环境可设置为false
    token-ttl-seconds: 604800
    token-key-prefix: "token:"
