spring:
  application:
    name: zadmin
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.9.105:43306/z-admin?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
#    username: z-admin
#    password: Zs2806478963
  datasource:
    dynamic:
      primary:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://192.168.9.105:35432/my_admin?currentSchema=public&reWriteBatchedInserts=true&stringtype=unspecified
        username: postgres
        password: Zs2806478963
        driver-class-name: org.postgresql.Driver
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.9.105:43306/z-ds1?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
        username: z-ds1
        password: Zs2806478963
        driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.9.105
      port: 46379
      password: Zs2806478963
      database: 0
      timeout: 5s
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 30
          # 连接池中的最小空闲连接
          min-idle: 10


logging:
  # 指定日志文件路径和名称（会自动创建 logs 文件夹在运行目录下）
  file:
    name: zlogs/zadmin.log
  # 配置日志滚动策略（可选）
  logback:
    rollingpolicy:
      max-file-size: 10MB    # 单个文件最大大小
      max-history: 30        # 保留历史日志的天数
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # 归档文件名格式
  level:
    com.easy.query: debug
